Initial commit
YaKirillKa/java-filmorate pull request #1
Opened 2022-08-01 17:09 UTC by YaKirillKa

2022-08-02 04:23 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isBlank()) {
Четыре строки ниже дублируются в методе update, можно вынести в метод.

2022-08-02 04:27 UTC, chewmag commented
По заданию нужно еще добавить тесты на валидацию:

«Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.»

2022-08-02 11:13 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isBlank()) {
Исправлено

2022-08-04 19:16 UTC, chewmag requested changes
Приветствую Кирилл!

Нужно залогировать операции создания/обновления данных, это требуется в задании.

2022-08-04 19:16 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Логгер добавлен, а вот логирования операций нет:

«Добавьте логирование для операций, которые изменяют сущности — добавляют и обновляют их. Также логируйте причины ошибок — например, если валидация не пройдена. Это считается хорошей практикой.»

2022-08-04 19:16 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Логгер добавлен, а вот логирования операций нет:

«Добавьте логирование для операций, которые изменяют сущности — добавляют и обновляют их. Также логируйте причины ошибок — например, если валидация не пройдена. Это считается хорошей практикой.»

2022-08-05 10:12 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Добавил

2022-08-05 10:12 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Добавил

2022-08-05 15:39 UTC, chewmag approved these changes
Логирование добавлено, можно двигаться дальше!

2022-08-05 15:39 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Got film with null ID: {}", film);
Наверное тут лучше использовать уровень error, а вообще логировать и кидать исключение считают плохой практикой https://www.theserverside.com/tip/Troubleshooting-Java-Code-Log-or-Re-Throw-but-Dont-Do-Both

2022-08-07 09:00 UTC, merged