feat: add-reviews 1
YaKirillKa/java-filmorate pull request #27
Opened 2022-10-06 20:23 UTC by Kazannik

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private static final String SELECT_LIKE_EXIST = "SELECT count(*) FROM review_likes WHERE is_like = ? AND review_id = ? AND user_id = ?";
Тут нужно поправить форматирование:
Идея рисует линию, за которую не рекомендуется заходить. Было бы здорово укладываться в нее и в запросах. 
Ты отлично уловил общий формат именования констант, но в одной пропустил _SQL. 
Обрати, пожалуйста, также внимание на регистр. Я старался придерживаться `UPPERCASE` для операторов и `lowercase` для столбцов. На мой взгляд - это упрощает чтение.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private static final String SELECT_LIKE_EXIST = "SELECT count(*) FROM review_likes WHERE is_like = ? AND review_id = ? AND user_id = ?";
У тебя есть пример `EXISTS()` выше, может тут тоже использовать его?

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +                    "FROM REVIEW r LEFT JOIN REVIEW_LIKES l ON l.review_id = r.id GROUP BY r.id HAVING r.id = ?";
У тебя вот эти четыре запроса практически идентичные, может попробовать вынести общую часть в отдельную переменную, а в методе в зависимости от параметров контатенировать строку с окончанием?

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private final RowMapper<Review> reviewMapper;
Кажется, что для ревью нет смысла писать свой маппер, поскольку все поля простые, достаточно использовать готовый `new BeanPropertyRowMapper<>(Review.class);` как это сделано в остальных простых сущностях.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        List<Review> reviews = jdbcTemplate.query(SELECT_LIMIT_SQL, reviewMapper, count);
Отдельная переменная не нужна, можно сразу возвращать, как ты делаешь в findByFilmId()

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        List<Review> reviews = jdbcTemplate.query(SELECT_ALL_SQL, reviewMapper);
Отдельная переменная не нужна, можно сразу возвращать, как ты делаешь в findByFilmId()

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            return reviewService.findAll().stream()
Бизнес-логики не должно быть в контроллере. Ее необходимо вынести на уровень сервиса.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addLike(@Valid @RequestBody(required = false) ReviewDto reviewDto, @PathVariable Long id, @PathVariable Long userId) {
А разве в данный PUT зачем-то надо передавать тело? Там же вся логика в запросе.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        }
Optional используется в возвращаемых значениях. В передаваемом совершенно нет смысла. Также на уровне контроллера не должно быть бизнес-логики. 
А поскольку тела в  у нас в принципе нет, то addLike в сервисе не должен принимать в себя ревью.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        reviewService.addLike(review, id, userId, false);
Optional используется в возвращаемых значениях. В передаваемом совершенно нет смысла. Также на уровне контроллера не должно быть бизнес-логики. 
А поскольку тела в  у нас в принципе нет, то addLike в сервисе не должен принимать в себя ревью.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        reviewService.removeLike(id, userId, true);
Поскольку пользователь не может поставить одновременно и лайк и дислайк фильму, третий параметр не нужен. Первичным ключем являются айдишники пользователя и ревью.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +}
Гитхаб подсказывает, что в конце файла должна быть пустая строка

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDao.java
> +     */
Круто, что добавил javadoc, еще круче, что сохранил стиль и точки. 
Было бы совсем шикарно, если бы добавил описание остальным методам.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDao.java
> +
Лишние разрывы строк стоит удалять, чтобы форматирование было однообразным.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
Когда уберешь логику из контроллера, она перейдет в сервис. Нужно подумать, как корректнее передать параметры таким образом, чтобы минимизировать однообразный код в DAO. В идеале, чтобы вызывался один метод в контроллере, в сервисе и DAO. Если не получится, то сервис определяет какие параметры передавать в какой метод DAO.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateExisting(review);
Нужно подумать над названием методов, сейчас выглядит так, что ты оба раза проверяешь существование review.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewDao.isLikeExist(reviewId, userId, isLike)) {
Для проверки существования не нужен третий параметр, ключем являются только айдишники.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (!filmService.existsById(filmId)) {
В принципе, я не вижу ничего плохого, чтобы использовать тут методы из DAO. Тогда все валидации будут одинаково проверять у слоя DAO существует ли та или иная сущность. И сервис не будет общаться с другими сервисами. И будет ненужным дополнительный метод в сервисе.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        }
Нет необходимости выполнять тут проверку полей. За проверку отвечает аннотация @Valid в контроллере и аннотации в DTO, посмотри, как это сделано в других местах. 
Также хочу обратить внимание на некорректность использования констант. 
В log аргументы замещают {} в строке-первом аргументе. А в исключение передается строка целиком. Посмотри, как это сделано в соседних методах. 
Но поскольку ты все это уничтожишь, комментарий выше только для понимания.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDto.java
> +    private Long useful;
Для однообразия рекомендую убрать лишние разрывы строк, и добавить одну между классом и первым полем. 
Необходимо корректно расставить аннотации валидации.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        Optional<Review> oldReview = findById(id);
В дао тебе не нужно получать предыдущее значение. Ты же получаешь ревью целиком, его и сохраняешь.

2022-10-07 19:52 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        review.setUseful(Optional.ofNullable(jdbcTemplate.queryForObject(SELECT_USEFUL_SQL, Long.class,
А когда ты только создаешь ревью, разве у него могу существовать лайки?

2022-10-07 20:24 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        Optional<Review> oldReview = findById(id);
Не соглашусь. По логике тестов postman в ревью можно изменить все кроме индексов пользователя и фильма. Я думаю это логично.

2022-10-07 20:32 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        review.setUseful(Optional.ofNullable(jdbcTemplate.queryForObject(SELECT_USEFUL_SQL, Long.class,
Ok! Заменил на 0L

2022-10-07 20:47 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private final RowMapper<Review> reviewMapper;
Review оказался не таким простым, у него виртуальное поле useful из другой таблицы, а также нужно как-то стыковать поле reviewId и столбец review.id. Я посчитал, что это как раз работа для спецализированного маппера.

2022-10-07 20:52 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        List<Review> reviews = jdbcTemplate.query(SELECT_LIMIT_SQL, reviewMapper, count);
Ok! Исправил.

2022-10-07 21:00 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addLike(@Valid @RequestBody(required = false) ReviewDto reviewDto, @PathVariable Long id, @PathVariable Long userId) {
Я посчитал, что логика addLike и addDislike вероятно должна быть идентична, и поскольку в тесте postman одновременно с добавлением  dislike передается тело, я сделал эти методы единообразными.

2022-10-07 21:15 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewDao.isLikeExist(reviewId, userId, isLike)) {
Этот метод совмещает лийки и диздайки. Поскольку ТЗ разделяет добавление-удаление лайков-дизлайков я разрешал это одним методом разделяя лайки и дизлайки параметром булевым isLike

2022-10-08 07:30 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +                    "FROM REVIEW r LEFT JOIN REVIEW_LIKES l ON l.review_id = r.id GROUP BY r.id HAVING r.id = ?";
Ок! Исправил.

2022-10-08 07:30 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private static final String SELECT_LIKE_EXIST = "SELECT count(*) FROM review_likes WHERE is_like = ? AND review_id = ? AND user_id = ?";
Ок! Да, отличная идея. Исправил.

2022-10-08 07:33 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        List<Review> reviews = jdbcTemplate.query(SELECT_ALL_SQL, reviewMapper);
Согласен. Осталось с отладки. Исправил.

2022-10-08 07:40 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDto.java
> +    private Long useful;
Не совсем понял про что ты, но думаю исправил.

2022-10-08 08:21 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            return reviewService.findAll().stream()
Ок! Перенес.

2022-10-08 08:32 UTC, kazakov93msk requested changes
Оставил 3 комментария, касательно доработки Insert/Update - не обязательно, просто вариант.

2022-10-08 08:32 UTC, kazakov93msk commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +                    "FROM REVIEW r LEFT JOIN REVIEW_LIKES l ON l.review_id = r.id GROUP BY r.id HAVING r.id = ?";
Нецелесообразное использование ресурсов базы. Речь о использовании HAVING. В твоем запросе получается, что ты сначала получаешь список всех фильмов, по каждому из них группируешь, а только затем отбираешь необходимые строки. Логично сначала найти нужный фильм и по нему уже группировать. Т.е. использовать WHERE clause. Аналогично и в других запросах.

2022-10-08 08:32 UTC, kazakov93msk commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        Optional<Review> oldReview = findById(id);
Как вариант, в данном случае использовать конструкцию INSERT INTP ... ON DUPLICATE KEY UPDATE field1 = value1, field2 = value2....
Но это просто вариант, если нет желания разбираться с этим, лучше оставить как есть.

2022-10-08 08:32 UTC, kazakov93msk commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +
Здесь стоит использовать аннотацию @NotBlank, для того, чтобы невозможно было передать отсутствующий контент или пустой (пробельный). Соответственно, используя в контроллере @Valid перед объектом ReviewDto сразу будет осуществляться проверка и необходимости на дополнительную проверку в сервисе на пустой контент не будет.

2022-10-08 08:34 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        }
Ок! Исправил.

2022-10-08 08:38 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        reviewService.addLike(review, id, userId, false);
Исправил. На счет боди уже писал. В тесте на дизлайк фигурирует боди. а для дизлайка нет. Исхожу из того, что они должны быть подобными, но отличающимися только вектором.

2022-10-08 08:44 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        reviewService.removeLike(id, userId, true);
У меня отрабатывает один метод, removeLike удаление и лайков и диздайков. Разница между лайком и дизлайком в третьем параметре.
Можно было бы построить логику по другому, но я исхожу из того, что поскольку удаление лайков и дизлайков по ТЗ в разных функциях, лучше бы проверять, а точно ли пользователь удаляет лайк.

2022-10-08 08:53 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDao.java
> +
Ок!

2022-10-08 08:55 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
Да. Подчистил.

2022-10-08 09:44 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        }
Ок! Исправил.

2022-10-08 09:59 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +}
Ок! Исправил, показалось самым простым.

2022-10-08 10:19 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +
Спасибо. Принято.

2022-10-08 10:31 UTC, Kazannik commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +                    "FROM REVIEW r LEFT JOIN REVIEW_LIKES l ON l.review_id = r.id GROUP BY r.id HAVING r.id = ?";
Идея понятна. Спасибо! Но Кирилл предложил ввести общую константу в 4 sql запроса и я уже закончил (

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void addLike(@Valid @RequestBody(required = false) ReviewDto reviewDto, @PathVariable Long id, @PathVariable Long userId) {
Все правильно сделал, вопросы именно к 
`@Valid @RequestBody(required = false) ReviewDto reviewDto`
Ни в одном из требований (доска и тесты) в лайки не передается тело, да в общем-то оно там и незачем. Поэтому я предлагаю его убрать. Будут эндпоинты и методы, аналогичные лайкам в фильмах.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +    private final RowMapper<Review> reviewMapper;
Я бы согласился про useful, но ты его получаешь непосредственно в запросе и итоговая таблица его содержит с тем же именованием, что и поле класса.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
> +        Optional<Review> oldReview = findById(id);
@Kazannik ага, посомтрел тесты, понял про что ты. 
У них некорректная логика, в таких случаях правильно было бы бросать CONFLICT в пользователя, чтобы он корректное тело присылал. 
Оставляем так.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/dao/review/ReviewDaoImpl.java
>          jdbcTemplate.update(INSERT_LIKE_SQL, reviewId, userId, isLike);
Логики в DAO тоже не должно быть. Ты же уже проверил, что ревью существует и корректно в сервисе. Сервис гарантирует, что в DAO уйдет корректный запрос.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (filmId != null && count != null) {
А у тебя же count не может быть null, в контроллере проставлено значение по умолчанию. А раз count не может быть null, у тебя всего два варианта - все отзывы с лимитом, либо все отзывы с лимитом, но к конкретному фильму.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (filmId != null && count != null) {
Else не нужны, поскольку у тебя сразу идет return, дальше код не будет выполняться. Поэтому они просто загромождают код.

2022-10-08 11:58 UTC, YaKirillKa commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewDao.isLikeExist(reviewId, userId, isLike)) {
Ага, понял о чем ты. Если пользователь поставил лайк, а пытается удалить дизлайк, все должно корректно отрабатывать. Согласен.

2022-10-08 16:45 UTC, kazakov93msk approved these changes
Всё ок

2022-10-08 17:01 UTC, YaKirillKa approved these changes

2022-10-08 17:28 UTC, merged